### PR TITLE
[Team MT2020 from China] Update soccerserver.rst

### PR DESCRIPTION
**Pull request by njqconquer**
we update some actions model in soccerserver.rst.

### CODE REVIEW

**Comment by hidehisaakiyama** [comment]
You just need to submit the changes of rst files.
Could you withdraw the changes for the automatically generated files (*.html, *.js and others)?
They may cause several conflicts.

**Comment by njqconquer** [comment]
I ’m sorry, I ’m not sure if I can withdraw the auto-generated files. Can you give us some guidance?

**Comment by hidehisaakiyama** [comment]
The easiest way is recreating new clone from the original repository. You can just need to copy the rst file from this branch to the new clone, then create a new pull request (and withdraw this pull request).

You can just overwrite generated files by original ones. After rewinding generated files, please commit and push the changes again. The changes will automatically applied to this pull request.

**Comment by njqconquer** [comment]
ok，Thank you.

**Pull request closed without merging**
