### PR TITLE
[Team ThunderLeague from Brazil] Update sections 6.1.1, 6.1.2, 6.1.3, 7.7.2

### PR DESCRIPTION
**Pull request by Pauloguilhermepp**
Adjusting formatting in sections 6.1.1, 6.1.2, 6.1.3, and 7.7.2.

### CODE REVIEW

**Comment by hidehisaakiyama** [comment]
Thanks for sending a pull request.
Unfortunately, section 3.8.1 is outdated content. Please remove that part from your changes.

**Comment by Pauloguilhermepp** [comment]
Excluding section 3.8.1, the current pull request just fixes formatting issues in different files. Do you think we should make more contributions or is that enough?

**Comment by hidehisaakiyama** [comment]
To be honest, we don't need the format correction that much, but I guess they would be acceptable.

It is preferred that the contributions are one of the changes not described in the old manual.
You can find current issues at https://github.com/rcsoccersim/manual/issues
And, there are the relevant TODO marks in the manual source.

If you try to tackle one of them, I recommend posting a comment on that issue page, in order to avoid conflict with others.

**Comment by Pauloguilhermepp** [comment]
I understand. We will make another pull request in the future solving an issue. Would it be better if we close this pull request or do you think it could be accepted?

**Comment by hidehisaakiyama** [comment]
Thanks. Could you close this PR?

**Pull request closed without merging**
