### PR TITLE
Added soccerwindow2.rst

### PR DESCRIPTION
**Pull request by mahdishemshadi**
Enigma team - Iran 
Mahdi Shemshadi
Zahra Bistouni
Reza Salehi
Yaser Pouzesh

### CODE REVIEW

**Comment by hidehisaakiyama** [comment]
soccerwindow2 is not an official component. As described in CFP, the documentation have to be ones related to the official soccer server.

**Comment by mahdishemshadi** [comment]
Enigma team - Iran
Mahdi Shemshadi
Zahra Bistouni
Reza Salehi
Yaser Pouzesh
updated coach and delete soccerwindow2

**Comment by mahdishemshadi** [comment]
Hi
I deleted soccerwindow2 and updated coach.
Please check if it is ok.
I will be thankful to you if you inform me as soon as possible.
with the best regards

**Comment by hidehisaakiyama** [comment]
It seems soccerwindow2.rst has not been deleted yet.
Could you check the state of your repository?

**Comment by mahdishemshadi** [comment]
How can I chek that? I did not wok with git so much
and another question
is the coach updated?

**Comment by hidehisaakiyama** [comment]
soccerwindow2.rst exists in your repository.  You can delete the file by following commands:
```
git rm soccerwindow2.rst
git commit -a
git push
```

**Comment by mahdishemshadi** [comment]
now please check again

**Comment by hidehisaakiyama** [comment]
Did you push your changes?
I can still find soccerwindow2.rst in your repository.

**Comment by mahdishemshadi** [comment]
I push
I opened a terminal in manual folder on my device and tried your commands
and now when I try git rm source/soccerwindow2.rst it says this name did not match any files

**Comment by mahdishemshadi** [comment]
Now I get clone again and there was not any soccerwindow2 in source file

**Comment by mahdishemshadi** [comment]
And now the coach did not update in the new clone

**Comment by mahdishemshadi** [comment]
and when I push fork there is no new fork for me 
what should I do now?
new coach is gone and gone soccerwindow2 dos not exist in my folders when I get new clone
I got confused

**Comment by hidehisaakiyama** [comment]
My observation is only your repository on github.
Is your current working copy is a clone of [your repository](https://github.com/mahdishemshadi/manual)?
Check the output of `git remote -v`

**Comment by mahdishemshadi** [comment]
I found the problem sir
now my question is that what should I do after command git commit -a?

**Comment by hidehisaakiyama** [comment]
Push your changes, then they will be reflected in this pull request.

**Comment by mahdishemshadi** [comment]
How do I change there?
I after git commit -a I got a new window on terminal named COMMIT_MSG
what should I do there?

**Comment by hidehisaakiyama** [comment]
How did you commit and push previous changes?
If you are using another git tool, please use it.
You just need to commit and push.

**Comment by mahdishemshadi** [comment]
Hi
I think now my repository should be correct.
I mean soccerwindow2 should be deleted and coach should be updated.
please check it and inform me about the situation

**Comment by mahdishemshadi** [comment]
and please check if the rcsoccersim repository is also updated bu my coach file and if it is ok with https://github.com/rcsoccersim/manual or not.
I will be thank full if you inform me what should I do now as soon as possible
with best regards

**Comment by mahdishemshadi** [comment]
Hi
I think now my repository should be correct.
I mean soccerwindow2 should be deleted and coach should be updated.
please check it and inform me about the situation
and please check if the rcsoccersim repository is also updated bu my coach
file and if it is ok with https://github.com/rcsoccersim/manual or not.
I will be thank full if you inform me what should I do now as soon as
possible
with best regards

**Comment by mahdishemshadi** [comment]
Hi
I can not see the changes I made in coach.rst.
It is my repository link
https://github.com/mahdishemshadi/manual/blob/master/source/coach.rst
what i changed are on my repository but I can not see it on
https://github.com/rcsoccersim/manual
please inform me about what is happening
with the best regards

**Comment by hidehisaakiyama** [comment]
We need to review your changes in order to approve your pull request. If something wrong, we will request you to fix it. This task takes a time. Wait for a while.

**Pull request closed without merging**
